import Vue from 'vue';
import Spinner from 'vue-simple-spinner';

import HeaderButton from './components/HeaderButton.vue';
import Breadcrumb from './components/Breadcrumb.vue';
import Avatar from './components/Avatar.vue';
import Modal from './components/Modal.vue';
import Blocker from './components/Blocker.vue';
import Loader from './components/Loader.vue';
import InvisibleLabel from './components/InvisibleLabel.vue';
import VButton from './components/VButton.vue';
import VCheckbox from './components/VCheckbox.vue';
import VInput from './components/VInput.vue';
import VSelect from './components/VSelect.vue';
import VRadio from './components/VRadio.vue';
import VSlider from './components/VSlider.vue';
import VTable from './components/VTable.vue';
import ListingExtension from './components/extensions/ListingExtension.vue';
import ListingOptionsExtension from './components/extensions/ListingOptionsExtension.vue';
import InterfaceExtension from './components/extensions/InterfaceExtension.vue';
import ReadonlyExtension from './components/extensions/ReadonlyExtension.vue';

Vue.component('header-button', HeaderButton);
Vue.component('breadcrumb', Breadcrumb);
Vue.component('spinner', Spinner);
Vue.component('avatar', Avatar);
Vue.component('modal', Modal);
Vue.component('blocker', Blocker);
Vue.component('loader', Loader);
Vue.component('invisible-label', InvisibleLabel);
Vue.component('v-button', VButton);
Vue.component('v-checkbox', VCheckbox);
Vue.component('v-input', VInput);
Vue.component('v-select', VSelect);
Vue.component('v-radio', VRadio);
Vue.component('v-slider', VSlider);
Vue.component('v-table', VTable);
Vue.component('listing-extension', ListingExtension);
Vue.component('listing-options-extension', ListingOptionsExtension);
Vue.component('interface-extension', InterfaceExtension);
Vue.component('readonly-extension', ReadonlyExtension);
