import Vue from 'vue';
import Spinner from 'vue-simple-spinner';

import Breadcrumb from './components/globals/Breadcrumb.vue';
import HeaderButton from './components/globals/HeaderButton.vue';
import InvisibleLabel from './components/globals/InvisibleLabel.vue';
import Loader from './components/globals/Loader.vue';
import VModal from './components/globals/VModal.vue';
import VAvatar from './components/globals/VAvatar.vue';
import VButton from './components/globals/VButton.vue';
import VCard from './components/globals/VCard.vue';
import VCheckbox from './components/globals/VCheckbox.vue';
import VDetails from './components/globals/VDetails.vue';
import VInput from './components/globals/VInput.vue';
import VRadio from './components/globals/VRadio.vue';
import VSelect from './components/globals/VSelect.vue';
import VSlider from './components/globals/VSlider.vue';
import VTable from './components/globals/VTable.vue';
import VTextarea from './components/globals/VTextarea.vue';

import InterfaceExtension from './components/extensions/InterfaceExtension.vue';
import ReadonlyExtension from './components/extensions/ReadonlyExtension.vue';
import ListingExtension from './components/extensions/ListingExtension.vue';
import ListingOptionsExtension from './components/extensions/ListingOptionsExtension.vue';

Vue.component('breadcrumb', Breadcrumb);
Vue.component('header-button', HeaderButton);
Vue.component('interface-extension', InterfaceExtension);
Vue.component('invisible-label', InvisibleLabel);
Vue.component('listing-extension', ListingExtension);
Vue.component('listing-options-extension', ListingOptionsExtension);
Vue.component('loader', Loader);
Vue.component('readonly-extension', ReadonlyExtension);
Vue.component('spinner', Spinner);
Vue.component('v-avatar', VAvatar);
Vue.component('v-button', VButton);
Vue.component('v-card', VCard);
Vue.component('v-checkbox', VCheckbox);
Vue.component('v-details', VDetails);
Vue.component('v-input', VInput);
Vue.component('v-modal', VModal);
Vue.component('v-radio', VRadio);
Vue.component('v-select', VSelect);
Vue.component('v-slider', VSlider);
Vue.component('v-table', VTable);
Vue.component('v-textarea', VTextarea);
