import Vue from "vue";
import Spinner from "vue-simple-spinner";

import VBreadcrumb from "./components/globals/v-breadcrumb.vue";
import HeaderButton from "./components/globals/v-header-button.vue";
import InvisibleLabel from "./components/globals/v-invisible-label.vue";
import Loader from "./components/globals/v-loader.vue";
import VModal from "./components/globals/v-modal.vue";
import VAvatar from "./components/globals/v-avatar.vue";
import VAlert from "./components/globals/v-alert.vue";
import VConfirm from "./components/globals/v-confirm.vue";
import VPrompt from "./components/globals/v-prompt.vue";
import VButton from "./components/globals/v-button.vue";
import VCard from "./components/globals/v-card.vue";
import VCheckbox from "./components/globals/v-checkbox.vue";
import VDetails from "./components/globals/v-details.vue";
import VInput from "./components/globals/v-input.vue";
import VRadio from "./components/globals/v-radio.vue";
import VSelect from "./components/globals/v-select.vue";
import VSlider from "./components/globals/v-slider.vue";
import VTable from "./components/globals/v-table.vue";
import VTextarea from "./components/globals/v-textarea.vue";

import VInterfaceExtension from "./components/extensions/v-interface-extension.vue";
import VReadonlyExtension from "./components/extensions/v-readonly-extension.vue";
import VListingExtension from "./components/extensions/v-listing-extension.vue";
import VListingOptionsExtension from "./components/extensions/v-listing-options-extension.vue";

Vue.component("v-breadcrumb", VBreadcrumb);
Vue.component("header-button", HeaderButton);
Vue.component("v-interface-extension", VInterfaceExtension);
Vue.component("invisible-label", InvisibleLabel);
Vue.component("v-listing-extension", VListingExtension);
Vue.component("v-listing-options-extension", VListingOptionsExtension);
Vue.component("loader", Loader);
Vue.component("v-readonly-extension", VReadonlyExtension);
Vue.component("spinner", Spinner);
Vue.component("v-avatar", VAvatar);
Vue.component("v-alert", VAlert);
Vue.component("v-confirm", VConfirm);
Vue.component("v-prompt", VPrompt);
Vue.component("v-button", VButton);
Vue.component("v-card", VCard);
Vue.component("v-checkbox", VCheckbox);
Vue.component("v-details", VDetails);
Vue.component("v-input", VInput);
Vue.component("v-modal", VModal);
Vue.component("v-radio", VRadio);
Vue.component("v-select", VSelect);
Vue.component("v-slider", VSlider);
Vue.component("v-table", VTable);
Vue.component("v-textarea", VTextarea);
